name: Github Actions workflow

on:
  push:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup runner workspace
        uses: actions/checkout@v3

  run-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: super-Linter
        uses: super-linter/super-linter@v7.2.0
            
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: demo shell script
        run: echo "Oh its ooon, Github Actions!! 🔥"
  